### ISSUE TITLE
Add sitenow_paragraphs to basic pages

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#72]
_relates to 2, 4, 7a - basic page, 8, on requirements document_

## Todo
Dev is overridden so I'll have to wait to package these settings.
- [ ] Update basic_page panelizer to include snp_content_blocks field.
- [ ] Add full-width-wrapper to default region.
- [ ] Add container wrapper to body content field.

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/commit/355b119a645bcadeabf9d387c0689ed966e2239c

**Comment by adamdelaney** [comment]
This is being blocked until we can resolve #75.

**Comment by adamdelaney** [comment]
@adriennecoon  I've added the Site Building Tools so that they are visible on pages now. You can see an example here: https://its.dev.drupal.uiowa.edu/node/111201. Anything that is added via the Site Building Tools will always show up before the pre-existing content.

Let me know if you have any questions.

**Comment by adamdelaney** [comment]
I tweaked some of the available widgets to be inline with what we offer other clients as well as remove some confusing options.

**Comment by adamdelaney** [comment]
I've moved the render for site building tools from above the body content to below. I've also fixed contrast ratio issues for buttons and unified the panel collapsible styles.

**Comment by joewhitsitt** [comment]
This has been reviewed and deployed.
